2021-01-27 16:11:59.018 75470 DEBUG nova.compute.manager [req-949c7fda-ca16-49b3-a8c7-9496f86892fa feb8f397e93d43a29889bafbf134dcef 540d75ce19604a9bb61e289585d1c986 - f50ac0bbd69c45c2885966b5c799bbf0 f50ac0bbd69c45c2885966b5c799bbf0] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Preparing to wait for external event network-vif-plugged-f6f5e6c5-2fdd-4719-9489-ca385d7fa7a7 prepare_for_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:327
2021-01-27 16:11:59.019 75470 DEBUG nova.compute.manager [req-949c7fda-ca16-49b3-a8c7-9496f86892fa feb8f397e93d43a29889bafbf134dcef 540d75ce19604a9bb61e289585d1c986 - f50ac0bbd69c45c2885966b5c799bbf0 f50ac0bbd69c45c2885966b5c799bbf0] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Preparing to wait for external event network-vif-plugged-1824336a-4bc3-46bb-9c08-bc86b1d24226 prepare_for_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:327
2021-01-27 16:12:02.798 75470 DEBUG nova.compute.manager [req-c53c8c9e-a2c2-466d-80ab-6364fd55a609 efe503c59aae4925bfc26898dc421480 836efddf6fe04ba8b37dcb4d8e177e97 - a683a58942244eb9b6032c7c427c7ad2 a683a58942244eb9b6032c7c427c7ad2] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Received event network-vif-plugged-f6f5e6c5-2fdd-4719-9489-ca385d7fa7a7 external_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:7886
2021-01-27 16:12:02.800 75470 DEBUG nova.compute.manager [req-c53c8c9e-a2c2-466d-80ab-6364fd55a609 efe503c59aae4925bfc26898dc421480 836efddf6fe04ba8b37dcb4d8e177e97 - a683a58942244eb9b6032c7c427c7ad2 a683a58942244eb9b6032c7c427c7ad2] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Processing event network-vif-plugged-f6f5e6c5-2fdd-4719-9489-ca385d7fa7a7 _process_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:7774
2021-01-27 16:12:04.861 75470 DEBUG nova.compute.manager [req-1d46124e-6e84-4643-89b5-54da1310239e efe503c59aae4925bfc26898dc421480 836efddf6fe04ba8b37dcb4d8e177e97 - a683a58942244eb9b6032c7c427c7ad2 a683a58942244eb9b6032c7c427c7ad2] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Received event network-vif-plugged-1824336a-4bc3-46bb-9c08-bc86b1d24226 external_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:7886
2021-01-27 16:12:04.865 75470 DEBUG nova.compute.manager [req-1d46124e-6e84-4643-89b5-54da1310239e efe503c59aae4925bfc26898dc421480 836efddf6fe04ba8b37dcb4d8e177e97 - a683a58942244eb9b6032c7c427c7ad2 a683a58942244eb9b6032c7c427c7ad2] [instance: d2666e01-73c8-4a97-9c22-0c175659e6db] Processing event network-vif-plugged-1824336a-4bc3-46bb-9c08-bc86b1d24226 _process_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:7774
2021-01-27 16:14:59.022 75470 DEBUG nova.compute.manager [req-b1d6f4ff-0145-45b0-8167-24ff7ddbfe62 e8bca730d8254a95b821eab7efc42db8 8ff7647db0df4ab48021e14a481beba2 - f89e92a9620e4b34ba448ec71387e692 f89e92a9620e4b34ba448ec71387e692] [instance: 5b367a10-9e6a-4eb9-9c7d-891dab7e87fa] Preparing to wait for external event network-vif-plugged-9a3673bf-58ac-423a-869a-6c4ae801b57b prepare_for_instance_event /usr/lib/python2.7/dist-packages/nova/compute/manager.py:327

